  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps (fresh, editable)
        env:
          PIP_NO_CACHE_DIR: "1"
        run: |
          python -m pip install -U pip
          # Ensure no stale wheel is hanging around
          pip uninstall -y vep-parser-mcp || true
          pip install -r parser-mcp/requirements.txt
          pip install -e parser-mcp[dev]

      - name: Sanity check CLIs
        run: |
          python -c "import vep_parser_mcp; print('vep_parser_mcp import OK')"
          python -m vep_parser_mcp.cli.filter_consequence_and_mane --help
          vep-filter-consequence-mane --help

      - name: Run tests
        run: pytest -q
